export enum UserEventType {
    USUARIO_CADASTRADO = 'USUARIO_CADASTRADO',
    ADMIN_CADASTRADO = 'ADMIN_CADASTRADO',
    USUARIO_LOGADO = 'USUARIO_LOGADO',
    USUARIO_DELETADO = 'USUARIO_DELETADO',
    SENHA_ALTERADA = 'SENHA_ALTERADA',
    EMAIL_USER_ALTERADO = 'EMAIL_USER_ALTERADO',

}